### ISSUE TITLE
[gitlab]:git clone not working by both https and ssh

### ISSUE THREAD

**Issue by kelvinji2009** [pabardina/docker-traefik-gitlab#1]
First of all, thanks for your sharing. 

### git clone with ssh
git clone ssh://git@gitlab.xxx.xxx:10022/kelvinji2009/demo.git
```
Cloning into 'demo'...
ssh: connect to host gitlab.xxx.xxx port 10022: Operation timed out
fatal: Could not read from remote repository.
```

### git clone with https
git clone https://kelvinji2009@gitlab.xxx.xxx:10080/kelvinji2009/demo.git
```
Cloning into 'demo'...
fatal: unable to access 'https://kelvinji2009@gitlab.xxx.xxx:10080/kelvinji2009/demo.git/': Failed to connect to gitlab.xxx.xxx port 10080: Operation timed out
```

**Comment by pabardz** [comment]
Hi ! 

### HTTP

I fixed the configuration for http. https://github.com/pabardina/docker-traefik-gitlab/commit/335674773cf3eae0e9a5a154342f05d86f5c4e7b
It should work now. There is no need to have a port in url. 
` git clone https://kelvinji2009@gitlab.xxx.xxx/kelvinji2009/demo.git`


### SSH
Hum.. there are some errors with old docker /compose version https://github.com/sameersbn/docker-gitlab/pull/658 

What is your docker and docker-compose version ? It could be a start for debugging

**Comment by kelvinji2009** [comment]
@pabardina Thanks for your reply. 

I am using the latest docker and docker-compose.
```
kelvinji@instance-1:~/mitnick/traefik-k2me$ docker -v
Docker version 17.03.1-ce, build c6d412e
kelvinji@instance-1:~/mitnick/traefik-k2me$ docker-compose -v
docker-compose version 1.12.0, build b31ff33
```

**Comment by kelvinji2009** [comment]
@pabardina It seems that `https` has been fixed.  Great. Thanks a lot.

**Comment by kelvinji2009** [comment]
@pabardina But `ssh` still not working.

**Comment by pabardz** [comment]
Simple question, is 10022 port allow  for incoming traffic on your instance ?

**Comment by kelvinji2009** [comment]
@pabardina Oh, my bad. I forgot to allow port 10022 in my firewall rules. Now it works fine. Thanks very much.
